### ISSUE TITLE
Not working for Hitman 2016 on Epic Store

### ISSUE THREAD

**Issue by Felixpaulsen** [OrfeasZ/Statman#15]
It doesn't seem to work with the epic store version. It just says "Waiting for game...".

Any help is much appreciated :)

**Comment by OrfeasZ** [comment]
This tool doesn't support Hitman 2016 (Epic version or otherwise) anymore, only Hitman 2 and even that is experimental. You can try using the latest build from [this issue](https://github.com/OrfeasZ/Statman/issues/7#issuecomment-496871452) but it will most likely not work or cause your game to crash.

**Comment by Felixpaulsen** [comment]
Oh, my bad. Latest build didn't work either, but thanks for answering so quickly.
