### ISSUE TITLE
Statman and everything it touches gets nuked by a good Antivirus

### ISSUE THREAD

**Issue by JohnnyNatrium** [OrfeasZ/Statman#5]
In fact there are so many issues popping up with a large array of affected files which my Bitdefender ends up blocking and/or destroying  (including Blood Money's main executable which is now gone, and several Nvidia related files) that I'm doubting whether I should even try to let it do its thing in full trust, especially because it also tries to connect to the internet.

Either way this kind of renders the app useless to me because unless I completely disable my antivirus and Advanced Threat Defenses forever, it'll nab one of the files whenever I turn anything on again.
The popular Hitman statistics tracker for SA and Contracts doesn't yield *any* response or problems from my antivirus, and it does all its tracking just fine.

Surely this should be workable without these issues. This App scores more Alerts than I do when I have Mass Murderer ratings.

**Comment by OrfeasZ** [comment]
The reason the other trackers don't get picked up by AVs is because they only read the game's memory. Statman actually injects code into the game (in memory, it doesn't even touch the game or any other files on your drive), which by some AVs is interpreted as malicious activity. I'll release a version signed with my personal code signing certificate, which could reduce the amount of false detections. I'll reply to this issue once that's done.

**Comment by OrfeasZ** [comment]
As for the internet access, it's not required. Statman only reaches out to the GitHub API to check if there's a newer release: https://github.com/OrfeasZ/Statman/blob/master/Statman/Util/UpdateChecker.cs#L92

**Comment by OrfeasZ** [comment]
@JohnnyNatrium try the signed build from here: https://github.com/OrfeasZ/Statman/releases/download/v1.3.3.0/Statman_1.3.3.0.zip. If that doesn't help I can submit samples to BitDefender for whitelisting.

**Comment by OrfeasZ** [comment]
I presume you no longer have this issue so I'm closing this.
